service:
  name: sls-saas-custom-authorizer

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  profile: smarly
  region: 'us-east-1'
  apiKeys:
    - mySecretAPIKey

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
          authorizer: authorizer
  authorizer:
    handler: handler.authorizer
