service:
  name: sls-saas-custom-authorizer

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: smarly
  region: 'us-east-1'
  apiKeys:
    - mySecretAPIKey

functions:
  authorizer:
    handler: handler.authorizer
