Resources:
  ElasticCacheCluster:
    DependsOn: SaaSStorageSecurityGroup
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AutoMinorVersionUpgrade: true
      Engine: redis
      CacheNodeType: ${self:custom.env.elasticache.CACHE_INSTANCE_SIZE.${self:provider.stage}}
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - "Fn::GetAtt": SaaSStorageSecurityGroup.GroupId
      CacheSubnetGroupName:
        Ref: SaaSCacheSubnetGroup
