app: sls-saas-user
service:
  name: sls-saas-user

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-stage-manager
  - serverless-domain-manager
  - serverless-package-external
  - serverless-pseudo-parameters

custom:
  PROJECT_NAME: "sls-saas"
  relativePathToCommon: "../common"
  packageExternal:
    external:
      - ${self:custom.relativePathToCommon}
  stages:
    - dev
    - staging
    - prod

  env: ${file(${self:custom.relativePathToCommon}/config-manager/env.yml)}
  prefix: ${file(${self:custom.relativePathToCommon}/config-manager/prefix.yml)}
  customDomain:
    basePath: users
    domainName: ${self:custom.env.serviceUrl.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs10.x
  vpc:
    securityGroupIds:
      - ${self:custom.env.vpc.securityGroupId.${self:provider.stage}}
    subnetIds:
      ${self:custom.env.vpc.subnetIds.${self:provider.stage}}
  stage: ${opt:stage, 'dev'}
  profile: smarly
  region: ${opt:region, 'us-east-1'}
  timeout: 15
  apiKeys:
    - userApiKey
  iamRoleStatements:
    # allow lambda invocation and request
    - Effect: "Allow"
      Action:
        - "lambda:InvoqueFunction"
      Resource: "*"
    # allow access dynamoDB base tenant
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "${self:custom.prefix.arn.table}/*"
        - "${self:custom.prefix.arn.sns}:${self:custom.env.snsTopic.${self:provider.stage}}"
    - Effect: "Allow"
      Action:
        - iam:*
        - s3:*
        - cognito-idp:*
        - cognito-sync:*
        - cognito-identity:*
        - sts:AssumeRole
      Resource: "*"

  environment:
    PROJECT_NAME: ${self:custom.PROJECT_NAME}
    SERVICE_URL: ${self:custom.env.serviceUrl.${self:provider.stage}}
    REGION: ${self:provider.region}
    SNS_ROLE_ARN: ${self:custom.prefix.arn.sns}:${self:custom.env.snsTopic.${self:provider.stage}}
    AWS_ACCOUNT_ID: ${self:custom.env.accountId.${self:provider.stage}}
    ENV: ${self:provider.stage}
    USER_TABLE: ${self:custom.env.table.user.${self:provider.stage}}
    TENANT_TABLE: ${self:custom.env.table.tenant.${self:provider.stage}}

functions:
  getUserPool:
    handler: handler.getUserPool
    events:
      - http:
          method: get
          path: pool/{id}
          cors:
            origin: "*"
  createUserSystem:
    handler: handler.createUserSystem
    events:
      - http:
          method: post
          path: system
          cors:
            origin: "*"
  createUserTenant:
    handler: handler.createUserTenant
    events:
      - http:
          method: post
          path: reg
          cors:
            origin: "*"
  createUser:
    handler: handler.createUser
    events:
      - http:
          method: post
          path: /
          cors:
            origin: "*"
          authorizer: ${self:custom.prefix.arn.lambda}:${self:custom.env.authorizer.${self:provider.stage}}
  listUser:
    handler: handler.listUser
    events:
      - http:
          path: /
          method: get
          cors: true
          authorizer: ${self:custom.prefix.arn.lambda}:${self:custom.env.authorizer.${self:provider.stage}}
  getUser:
    handler: handler.getUser
    events:
      - http:
          method: get
          path: /{id}
          cors:
            origin: "*"
          authorizer: ${self:custom.prefix.arn.lambda}:${self:custom.env.authorizer.${self:provider.stage}}
  delUserTenants:
    handler: handler.delUserTenants
    events:
      - http:
          method: delete
          path: tenants
          cors:
            origin: "*"
  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: /
          method: put
          cors:
            origin: "*"
          authorizer: ${self:custom.prefix.arn.lambda}:${self:custom.env.authorizer.${self:provider.stage}}
  enableUser:
    handler: handler.enableUser
    events:
      - http:
          path: enable
          method: put
          cors:
            origin: "*"
          authorizer: ${self:custom.prefix.arn.lambda}:${self:custom.env.authorizer.${self:provider.stage}}
  disableUser:
    handler: handler.disableUser
    events:
      - http:
          path: disable
          method: put
          cors:
            origin: "*"
          authorizer: ${self:custom.prefix.arn.lambda}:${self:custom.env.authorizer.${self:provider.stage}}
  delUser:
    handler: handler.delUser
    events:
      - http:
          path: /{id}
          method: delete
          cors:
            origin: "*"
          authorizer: ${self:custom.prefix.arn.lambda}:${self:custom.env.authorizer.${self:provider.stage}}
  delUserTables:
    handler: handler.delUserTables
    events:
      - http:
          path: tables
          method: delete
          cors:
            origin: "*"
          authorizer: ${self:custom.prefix.arn.lambda}:${self:custom.env.authorizer.${self:provider.stage}}


# create our resources with separate cloudFormation Templates
resources:
  # API Gateway Errors and CORS
  - ${file(${self:custom.relativePathToCommon}/config-manager/resources/api-gateway-auth-errors.yml)}
